CREATE DATABASE productos;

-- TABLA CATEGORÍA
CREATE TABLE categoria
(
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(50) NOT NULL UNIQUE
);

-- TABLA MARCA
CREATE TABLE marca
(
    id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(50) NOT NULL UNIQUE
);

-- TABLA IMAGEN
CREATE TABLE image (
    id_img INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url    VARCHAR(500) NOT NULL
);

-- TABLA PRODUCTO
CREATE TABLE producto (
    id_producto  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100)   NOT NULL,
    precio       DECIMAL(10, 2) NOT NULL CHECK (precio > 0),
    descripcion  VARCHAR(255)   NOT NULL,
    stock        INT            NOT NULL CHECK (stock >= 0),
    id_categoria INT            NOT NULL REFERENCES categoria (id_categoria) ON DELETE CASCADE,
    id_marca     INT            NOT NULL REFERENCES marca (id_marca) ON DELETE CASCADE,
    id_img       INT            REFERENCES image (id_img) ON DELETE SET NULL
);

-- Insertar categorías
INSERT INTO categoria (nombre) VALUES
('Running'),
('Basketball'),
('Skateboarding'),
('Lifestyle'),
('Training & Gym'),
('Outdoor & Hiking'),
('Fútbol'),
('Sandals & Slides'),
('Golf'),
('Tenis');

-- Insertar marcas
INSERT INTO marca (nombre) VALUES
('Nike'),
('Adidas'),
('Jordan'),
('New Balance'),
('Puma'),
('Converse'),
('Vans'),
('Reebok'),
('Under Armour'),
('ASICS');

-- Insertar imágenes
INSERT INTO image (url) VALUES
-- Nike Air Zoom Pegasus 41
('https://www.nike.com.pe/dw/image/v2/BJKZ_PRD/on/demandware.static/-/Sites-catalog-equinox/default/dw057b791d/images/hi-res/197863039411_1_20250403-mrtPeru.jpg?sw=800&sh=800'),

-- Adidas Ultraboost 22
('https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/d2a64cf9cd824e5d9fcc950b5eb0b2c8_9366/Zapatillas_Ultraboost_5_Azul_ID8817_HM1.jpg'),

-- New Balance Fresh Foam 1080v12
('https://newbalance.com.pe/media/catalog/product/z/a/zapatillas-hombre-newbalance-m1080l14-0_1_qxjuwpyslas3lhg8.jpg?optimize=medium&bg-color=255,255,255&fit=bounds&height=1000&width=1000&canvas=1000:1000'),

-- ASICS Gel-Kayano 29
('https://dojiw2m9tvv09.cloudfront.net/54753/product/1012b272-402-sr-rt-glb7801.jpg'),

-- Jordan 1 Retro High
('https://www.nike.com.pe/on/demandware.static/-/Sites-catalog-equinox/default/dwa1e00c04/images/img/DV1748_601_A_PREM.jpeg'),

-- Under Armour Curry Flow 10
('https://images-cdn.ubuy.pe/64baffa25f91f92316759f30-under-armour-curry-flow-10-iron-sharpens.jpg'),

-- Vans Old Skool
('https://media.lotsthailand.com/media/wysiwyg/Content/12345b6ae523d99089bd3388a8aefcfe.png'),

-- Nike SB Dunk Low
('https://futurevisions.pe/33141-large_default/nike-sb-dunk-low-pro-grey.jpg'),

-- Nike Air Force 1 07
('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuqW6GxT1NIrIO3WqrBcj10_zvilECqQ6GEg&s'),

-- Adidas Samba OG
('https://assets.adidas.com/images/w_600,f_auto,q_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Zapatillas_Samba_OG_Blanco_B75806_01_00_standard.jpg'),

-- New Balance 550
('https://home.ripley.com.pe/Attachment/WOP_5/2026333669811/2026333669811_2.jpg'),

-- Puma Suede Classic
('https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,e_sharpen:95,w_2000,h_2000/global/399853/01/sv01/fnd/PER/fmt/png/Zapatillas-para-juniors-Suede-Classic'),

-- Converse Chuck Taylor All Star
('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyJtwG2bBtOED-1dSCGWnAwSMcVZdab9wY6A&s'),

-- Reebok Nano X2
('https://www.thenextsole.com/storage/images/GX9916.png'),

-- Nike Metcon 9
('https://www.nike.com.pe/on/demandware.static/-/Sites-catalog-equinox/default/dw5568dd9a/images/hi-res/196607709269_1_20240129120000-mrtPeru.jpeg'),

-- Adidas Copa Sense
('https://assets.adidas.com/images/w_600,f_auto,q_auto/80542ca59a9a4e04bd22ac39010ca5f4_9366/COPA_SENSE.3_TF_Negro_FW6530_01_standard.jpg'),

-- Nike Mercurial Vapor 15
('https://www.nike.com.pe/on/demandware.static/-/Sites-catalog-equinox/default/dwb3ac8db7/images/hi-res/196975715190_1_20240305120000-mrtPeru.jpeg');


-- Insertar productos
INSERT INTO producto (nombre, precio, descripcion, stock, id_categoria, id_marca) VALUES
-- Running / id_categoria = 1
('Nike Air Zoom Pegasus 41', 629.00, 'Zapatillas de running con amortiguación Zoom Air ReactX para mayor suavidad y respuesta.', 90, 1, 1),
('Adidas Ultraboost 22', 599.00, 'Zapatillas de running con suela Boost para alto rendimiento y comodidad.', 70, 1, 2),
('New Balance Fresh Foam 1080v12', 164.99, 'Zapatillas de running con máxima amortiguación Fresh Foam para distancias largas.', 32, 1, 4),
('ASICS Gel-Kayano 29', 159.99, 'Zapatillas de running con estabilidad y tecnología Gel para una pisada estable.', 28, 1, 10),

-- Basketball / id_categoria = 2
('Jordan 1 Retro High', 179.99, 'Zapatillas de baloncesto de edición limitada, ícono del streetwear.', 25, 2, 3),
('Under Armour Curry Flow 10', 159.99, 'Zapatillas de baloncesto de alto rendimiento con tracción superior.', 20, 2, 9),

-- Skateboarding / id_categoria = 3
('Vans Old Skool', 69.99, 'Zapatillas de skate con la icónica franja lateral y suela de goma waffle.', 85, 3, 7),
('Nike SB Dunk Low', 109.99, 'Zapatilla de skateboarding con estilo retro y gran amortiguación.', 45, 3, 1),

-- Lifestyle / id_categoria = 4
('Nike Air Force 1 07', 119.99, 'Zapatilla urbana clásica de cuero con amortiguación Air.', 50, 4, 1),
('Adidas Samba OG', 89.99, 'Zapatilla clásica de fútbol indoor, convertida en un ícono de estilo urbano.', 65, 4, 2),
('New Balance 550', 119.99, 'Zapatilla lifestyle inspirada en el baloncesto vintage.', 40, 4, 4),
('Puma Suede Classic', 79.99, 'Zapatilla urbana de gamuza con un estilo retro y versátil.', 60, 4, 5),
('Converse Chuck Taylor All Star', 64.99, 'Zapatilla de lona clásica, ícono del estilo casual y streetwear.', 75, 4, 6),

-- Training & Gym / id_categoria = 5
('Reebok Nano X2', 134.99, 'Zapatilla de entrenamiento para cross training y actividades de gimnasio.', 30, 5, 8),
('Nike Metcon 9', 579.00, 'Zapatillas de entrenamiento de alta intensidad y gran estabilidad.', 60, 5, 1),

-- Fútbol / id_categoria = 7
('Adidas Copa Sense', 229.99, 'Botines de fútbol con toque descalzo y máximo control del balón.', 15, 7, 2),
('Nike Mercurial Vapor 15', 274.99, 'Botines de fútbol ligeros para jugadores que buscan velocidad.', 12, 7, 1);

-- Actualizar cada producto con su id_img correspondiente
UPDATE producto SET id_img = 1 WHERE id_producto = 1; -- Nike Air Zoom Pegasus 41
UPDATE producto SET id_img = 2 WHERE id_producto = 2; -- Adidas Ultraboost 22
UPDATE producto SET id_img = 3 WHERE id_producto = 3; -- New Balance Fresh Foam 1080v12
UPDATE producto SET id_img = 4 WHERE id_producto = 4; -- ASICS Gel-Kayano 29
UPDATE producto SET id_img = 5 WHERE id_producto = 5; -- Jordan 1 Retro High
UPDATE producto SET id_img = 6 WHERE id_producto = 6; -- Under Armour Curry Flow 10
UPDATE producto SET id_img = 7 WHERE id_producto = 7; -- Vans Old Skool
UPDATE producto SET id_img = 8 WHERE id_producto = 8; -- Nike SB Dunk Low
UPDATE producto SET id_img = 9 WHERE id_producto = 9; -- Nike Air Force 1 07
UPDATE producto SET id_img = 10 WHERE id_producto = 10; -- Adidas Samba OG
UPDATE producto SET id_img = 11 WHERE id_producto = 11; -- New Balance 550
UPDATE producto SET id_img = 12 WHERE id_producto = 12; -- Puma Suede Classic
UPDATE producto SET id_img = 13 WHERE id_producto = 13; -- Converse Chuck Taylor All Star
UPDATE producto SET id_img = 14 WHERE id_producto = 14; -- Reebok Nano X2
UPDATE producto SET id_img = 15 WHERE id_producto = 15; -- Nike Metcon 9
UPDATE producto SET id_img = 16 WHERE id_producto = 16; -- Adidas Copa Sense
UPDATE producto SET id_img = 17 WHERE id_producto = 17; -- Nike Mercurial Vapor 15

-- Insertar productos
INSERT INTO producto (nombre, precio, descripcion, stock, id_categoria, id_marca, id_img) VALUES
-- Running
('Nike Air Zoom Pegasus 40', 499.90, 'Zapatillas de running ligeras y cómodas con excelente amortiguación.', 25, 1, 1, https://runastore.pe/media/catalog/product/cache/1ad426beaceeac5935cd76675f3d6a1f/d/v/dv3853-100_1.jpg),
('Adidas Ultraboost Light', 629.00, 'Zapatillas de alto rendimiento con tecnología Boost para máxima energía.', 18, 1, 2, https://m.media-amazon.com/images/I/71hzKt-KuoL._AC_SL1500_.jpg),

-- Basketball
('Jordan Luka 2', 699.90, 'Diseñadas para el juego rápido, con gran soporte lateral.', 15, 2, 3, https://totalsport.pe/wp-content/uploads/DZ3498-100-1.jpg),
('Puma All Pro Nitro', 449.00, 'Zapatillas de baloncesto con suela de tracción multidireccional.', 12, 2, 5, https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,e_sharpen:95,w_2000,h_2000/global/379924/01/sv01/fnd/PER/fmt/png/Zapatillas-de-basketball-All-Pro-NITRO%E2%84%A2-unisex),

-- Skateboarding
('Vans Old Skool Pro', 319.00, 'Modelo clásico reforzado para skaters, con suela waffle.', 30, 3, 7, https://vans.com.pe/cdn/shop/files/VN000D3HY28-HERO.jpg?v=1753832694&width=493),
('Nike SB Dunk Low', 549.90, 'Zapatillas de skate con diseño icónico y gran agarre.', 20, 3, 1, https://totalsport.pe/wp-content/uploads/FQ7585-200-1.jpg),

-- Lifestyle
('New Balance 574 Classic', 389.00, 'Estilo retro con comodidad moderna, ideal para el día a día.', 40, 4, 4, https://sparta.pe/wp-content/uploads/ml574evn_2-1.jpg),
('Adidas Stan Smith', 359.90, 'Clásico atemporal con acabado en cuero y detalles minimalistas.', 35, 4, 2, https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/4edaa6d5b65a40d19f20a7fa00ea641f_9366/Zapatillas_Stan_Smith_Blanco_M20325_01_standard.jpg),

-- Training & Gym
('Reebok Nano X4', 499.00, 'Diseñadas para entrenamiento funcional y levantamiento de pesas.', 25, 5, 8, https://rimage.ripley.com.pe/home.ripley/Attachment/WOP/1/2084346037546/full_image-2084346037546.jpg),
('Under Armour Project Rock 6', 569.90, 'Zapatillas de entrenamiento con gran estabilidad y durabilidad.', 15, 5, 9, https://runastore.pe/media/catalog/product/cache/715c0a09f6185a203cf9660960f0d1a6/3/0/3026534-800_1.jpg),

-- Outdoor & Hiking
('ASICS Gel-Sonoma 7', 429.00, 'Zapatillas de trail con amortiguación y tracción para terrenos difíciles.', 22, 6, 10, https://media.falabella.com/falabellaPE/20676578_1/public),
('Nike ACG Air Nasu 2', 579.90, 'Zapatillas todoterreno resistentes al agua y de gran agarre.', 10, 6, 1, https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAGrijYXkg6RN93WSVywY7SWNmQzzzOgt-jA&s),

-- Fútbol
('Adidas Predator Accuracy.3 FG', 449.00, 'Botines para césped natural con ajuste cómodo y precisión al golpear.', 20, 7, 2, https://assets.adidas.com/images/w_600,f_auto,q_auto/2400a061370347378232f0e5681eb250_9366/Chimpunes_Predator_Accuracy.3_Terreno_Firme_Azul_GZ0026_22_model.jpg),
('Puma Future 7 Ultimate FG/AG', 499.00, 'Botines ligeros con cordones personalizables y control superior.', 18, 7, 5, https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,e_sharpen:95,w_2000,h_2000/global/107599/03/sv01/fnd/PER/fmt/png/FUTURE-7-ULTIMATE-Firm-Ground/Artificial-Ground-Men's-Soccer-Cleats),

-- Sandals & Slides
('Nike Victori One Slide', 159.90, 'Sandalias ligeras y acolchadas para después del entrenamiento.', 35, 8, 1, https://d3fvqmu2193zmz.cloudfront.net/ProductCatalog/Workspace.CWDQQL6GUIJMS/ProductCatalog.C2GW32EBR2OYS/500x500/C2GXKBJJ2VQMG.jpg),
('Adidas Adilette Aqua', 139.90, 'Sandalias resistentes al agua con plantilla suave.', 40, 8, 2, https://assets.adidas.com/images/w_600,f_auto,q_auto/cb1316406e584892bdb3a991001bd46d_faec/Sandalias_adilette_Aqua_Negro_F35543_db01_standard.jpg),

-- Golf
('Under Armour HOVR Drive 2', 729.00, 'Zapatillas de golf con tracción y soporte premium.', 8, 9, 9, https://m.media-amazon.com/images/I/71UIRBsxd8L._UY900_.jpg),
('Puma Ignite PWRAdapt Caged', 649.90, 'Zapatillas de golf con amortiguación adaptable y gran agarre.', 10, 9, 5, https://m.media-amazon.com/images/I/71AAeb6+6PL._AC_SL1500_.jpg),

-- Tenis
('ASICS Court FF 3', 589.00, 'Zapatillas de tenis con gran estabilidad y amortiguación.', 12, 10, 10, https://media.falabella.com/falabellaPE/138034130_01/w=800,h=800,fit=pad),
('NikeCourt Air Zoom Vapor 11', 629.00, 'Diseño ligero y ágil para jugadores rápidos.', 14, 10, 1, https://http2.mlstatic.com/D_NQ_NP_703470-MPE71509680231_092023-O-zapatilla-nike-nikecourt-air-zoom-vapor-11-dr6965800-.webp);



select *
from categoria;

select *
from marca;

select *
from image;

select *
from producto;

SELECT p.nombre AS producto,
       c.nombre AS categoria,
       m.nombre AS marca
FROM producto p
         INNER JOIN categoria c ON p.id_categoria = c.id_categoria
         INNER JOIN marca m ON p.id_marca = m.id_marca;