CREATE DATABASE productos;

CREATE TABLE categoria
(
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(50) NOT NULL
);

CREATE TABLE marca
(
    id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(50) NOT NULL
);

CREATE TABLE producto
(
    id_producto  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100)   NOT NULL,
    precio       DECIMAL(10, 2) NOT NULL,
    descripcion  VARCHAR(255)   NOT NULL,
    stock        INT            NOT NULL,
    id_categoria INT            NOT NULL REFERENCES categoria (id_categoria) ON DELETE CASCADE,
    id_marca     INT            NOT NULL REFERENCES marca (id_marca) ON DELETE CASCADE
);

-- INSERTAR CATEGORÍAS
INSERT INTO categoria (nombre)
VALUES ('Smartphones'),
       ('Laptops'),
       ('Tablets'),
       ('Auriculares'),
       ('Monitores');

-- INSERTAR MARCAS
INSERT INTO marca (nombre)
VALUES ('Samsung'),
       ('Apple'),
       ('Xiaomi'),
       ('Asus'),
       ('Logitech');

-- INSERTAR PRODUCTOS
INSERT INTO producto (nombre, precio, descripcion, stock, id_categoria, id_marca)
VALUES ('Samsung Galaxy S24 Ultra', 4500.00, 'Smartphone gama alta, 512GB, 12GB RAM', 50, 1, 1),
       ('iPhone 15 Pro Max', 5000.00, 'Smartphone gama premium, 512GB, 8GB RAM', 30, 1, 2),
       ('Xiaomi Pad 6', 1800.00, 'Tablet de alto rendimiento, 256GB, 8GB RAM', 40, 3, 3),
       ('Asus ROG Strix G513RM', 7000.00, 'Laptop gaming, Ryzen 7, 16GB RAM, RTX 4060', 20, 2, 4),
       ('Logitech MX Master 3', 450.00, 'Mouse inalámbrico ergonómico', 100, 4, 5),
       ('Samsung Odyssey G8 32"', 3500.00, 'Monitor gaming 32", 240Hz, UHD', 15, 5, 1),
       ('Apple MacBook Air M2', 5500.00, 'Laptop ultraligera, M2, 16GB RAM, 512GB', 25, 2, 2),
       ('Logitech G733', 650.00, 'Auriculares inalámbricos gaming RGB', 60, 4, 5);


select *
from categoria;

select *
from producto;