CREATE DATABASE carrito;

-- Tabla de carrito
CREATE TABLE carrito (
    id_carrito INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total DECIMAL(10,2) DEFAULT 0
);

-- Tabla de items del carrito
CREATE TABLE item_carrito (
    id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito INT NOT NULL REFERENCES carrito(id_carrito) ON DELETE CASCADE,
    id_producto INT NOT NULL,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    precio_unitario DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    fecha_agregado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para mejor performance
CREATE INDEX idx_carrito_usuario ON carrito(id_usuario);
CREATE INDEX idx_item_carrito ON item_carrito(id_carrito);
CREATE INDEX idx_item_producto ON item_carrito(id_producto);